[package]
authors = ['Narrowlink <opensource@narrowlink.com>']
description = 'Asynchronous lightweight implementation of TCP/IP stack for Tun device'
name = "ipstack"
version = "0.0.5"
edition = "2021"
license = "Apache-2.0"
repository = 'https://github.com/narrowlink/ipstack'
# homepage = 'https://github.com/narrowlink/ipstack'
readme = "README.md"

[features]
default = []
log = ["tracing/log"]

[dependencies]
tokio = { version = "1.36", features = [
    "sync",
    "rt",
    "time",
    "io-util",
    "macros",
], default-features = false }
etherparse = { version = "0.14", default-features = false, features = ["std"] }
thiserror = { version = "1.0", default-features = false }
tracing = { version = "0.1", default-features = false, features = [
    "log",
], optional = true }
rand = {version = "0.8.5", default-features = false, features = ["std","std_rng"] }

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
udp-stream = { version = "0.0", default-features = false }
tokio = { version = "1.36", features = [
    "rt-multi-thread",
], default-features = false }


#tun2.rs example
tun2 = { version = "1.2", features = ["async"] }

#tun_wintun.rs example
[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dev-dependencies]
tun = { version = "0.6.1", features = ["async"], default-features = false }
[target.'cfg(target_os = "windows")'.dev-dependencies]
wintun = { version = "0.4", default-features = false }

[profile.release]
opt-level = 'z'          # Optimize for size.
lto = true               # Enable Link Time Optimization
codegen-units = 1        # Reduce number of codegen units to increase optimizations.
panic = "abort"          # Abort on panic
debug = false            # Strip debug symbols from the binary.
rpath = false            # Do not embed the path to the dynamic library in the binary.
debug-assertions = false # Remove assertions from the binary.
incremental = false      # Disable incremental compilation.
overflow-checks = false  # Disable overflow checks.
strip = true             # Automatically strip symbols from the binary.

[[example]]
name = "tun2"
required-features = ["log"]
