[package]
authors = ['Sajjad Pourali <sajjad@pourali.com>']
description = 'Asynchronous lightweight implementation of TCP/IP stack for Tun device'
name = "ipstack"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
repository = 'https://github.com/SajjadPourali/ipstack'
# homepage = 'https://github.com/SajjadPourali/ipstack'
readme = "README.md"

[dependencies]
tokio = { version = "1.33", features = [
    "sync",
    "rt",
    "time",
    "io-util",
    "macros",
], default-features = false }
etherparse = { version = "0.13", default-features = false }
thiserror = { version = "1.0", default-features = false }

[dev-dependencies]
udp-stream = { version = "0.0.9", default-features = false }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dev-dependencies]
tun = { version = "0.6", features = ["async"], default-features = false }

[target.'cfg(target_os = "windows")'.dev-dependencies]
wintun = { version = "0.3", default-features = false }

[profile.release]
opt-level = 'z'          # Optimize for size.
lto = true               # Enable Link Time Optimization
codegen-units = 1        # Reduce number of codegen units to increase optimizations.
panic = "abort"          # Abort on panic
debug = false            # Strip debug symbols from the binary.
rpath = false            # Do not embed the path to the dynamic library in the binary.
debug-assertions = false # Remove assertions from the binary.
incremental = false      # Disable incremental compilation.
overflow-checks = false  # Disable overflow checks.
strip = true             # Automatically strip symbols from the binary.
